# ===================================
#  List Behavior Config
# ===================================

modelClass: Majos\Conference\Models\Venue
title: Manage Venues
list: $/majos/conference/models/Venue/columns.yaml
recordUrl: majos/conference/venues/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showPageNumbers: true
showSetup: true
showSorting: true
defaultSort:
    column: sort_order
    direction: asc
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt